Day25_Backend/ToDoListApp - Day 2/Entities/Assignment.cs
// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ToDoListApp.Entities;

public partial class Assignment
{
    public int AssignmentId { get; set; }

    public string CreatedBy { get; set; }

    public string AssignedTo { get; set; }

    public virtual ICollection<ToDoTask> ToDoTasks { get; set; } = new List<ToDoTask>();
}

Day25_Backend/ToDoListApp - Day 2/Entities/ToDoListContext.cs
// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace ToDoListApp.Entities;

public partial class ToDoListContext : DbContext
{
    public ToDoListContext()
    {

    }
    public ToDoListContext(DbContextOptions<ToDoListContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Assignment> Assignments { get; set; }

    public virtual DbSet<ToDoTask> ToDoTasks { get; set; }
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see http://go.microsoft.com/fwlink/?LinkId=723263.
       => optionsBuilder.UseSqlServer("Data Source=KRASTEVCM\\SQLEXPRESS2019;Initial Catalog=ToDoList;Integrated Security=True;Encrypt=True;TrustServerCertificate=True");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Assignment>(entity =>
        {
            entity.HasKey(e => e.AssignmentId).HasName("PK_Assignmets");

            entity.Property(e => e.AssignedTo).HasMaxLength(50);
            entity.Property(e => e.CreatedBy).HasMaxLength(50);
        });

        modelBuilder.Entity<ToDoTask>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_Tasks");

            entity.Property(e => e.Date).HasColumnType("datetime");
            entity.Property(e => e.Done).HasDefaultValueSql("((0))");
            entity.Property(e => e.Name).HasMaxLength(50);

            entity.HasOne(d => d.Assingment).WithMany(p => p.ToDoTasks)
                .HasForeignKey(d => d.AssingmentId)
                .HasConstraintName("FK_Tasks_Assignments");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}

Day25_Backend/ToDoListApp - Day 2/Entities/ToDoTask.cs
// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ToDoListApp.Entities;

public partial class ToDoTask
{
    public int Id { get; set; }

    public string Name { get; set; }

    public DateTime? Date { get; set; }

    public bool? Done { get; set; }

    public int? AssingmentId { get; set; }

    public virtual Assignment Assingment { get; set; }
}

Day25_Backend/ToDoListApp - Day 2/Models/Assignment.cs
namespace ToDoListApp.Models
{
    public class Assignment
    {
        public int AssignmentId { get; set; }
        public string CreatedBy { get; set; }
        public string AssignedTo { get; set; }

        public virtual List<ToDoTask> Tasks { get; set; }

        public Assignment(int assignmentId, string createdBy, string assignedTo)
        {
            AssignmentId = assignmentId;
            CreatedBy = createdBy;
            AssignedTo = assignedTo;
        }

        public Assignment()
        {
        }
    }
}

Day25_Backend/ToDoListApp - Day 2/Models/ErrorViewModel.cs
namespace ToDoListApp.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Day25_Backend/ToDoListApp - Day 2/Models/ToDoTask.cs
namespace ToDoListApp.Models
{
    public class ToDoTask
    {
        public int TaskId { get; set; }
        public string Name { get; set; }
        public DateTime CreatedOn { get; set; }
        public bool? Done { get; set; }
        public string Description { get; set; }
        public int AssignmentId { get; set; }
        public virtual Assignment Assignment { get; set; }

        public ToDoTask(int taskId, string name, DateTime createdOn, bool? done, string description, int assignmentId)
        {
            TaskId = taskId;
            Name = name;
            CreatedOn = createdOn;
            Done = done;
            Description = description;
            AssignmentId = assignmentId;
        }
        public ToDoTask(int taskId, string name, DateTime createdOn, bool? done, string description, int assignmentId, Assignment assignment)
        {
            TaskId = taskId;
            Name = name;
            CreatedOn = createdOn;
            Done = done;
            Description = description;
            AssignmentId = assignmentId;
            Assignment = assignment;
        }

        public ToDoTask()
        {
        }
    }
}

Day25_Backend/ToDoListApp - Day 2/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using ToDoListApp.Models;

namespace ToDoListApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Day25_Backend/ToDoListApp - Day 2/Controllers/ToDoTaskController.cs
using Microsoft.AspNetCore.Mvc;
using ToDoTask = ToDoListApp.Entities.ToDoTask;

using ToDoListApp.Entities;

namespace ToDoListApp.Controllers
{
    public class ToDoTaskController : Controller
    {
        public IActionResult Index()
        {
            List<ToDoTask> tasks = new List<ToDoTask>();

            using(ToDoListContext context = new ToDoListContext())
            {
                tasks = (from task in context.ToDoTasks
                             join assignment in context.Assignments
                                on task.AssingmentId equals assignment.AssignmentId
                             select new ToDoTask
                             {
                                 Id = task.Id,
                                 Name = task.Name,
                                 Date = task.Date,
                                 Done = task.Done,
                                 Assingment = assignment
                             }).ToList();

            }

            return View(tasks);
        }

        public IActionResult Create()
        {
            return View();
        }

        public IActionResult CreateNewTask(ToDoTask task)
        {
            ToDoTask taskToAdd = new ToDoTask();

            using(ToDoListContext context = new ToDoListContext())
            {
                taskToAdd.Name = task.Name;
                taskToAdd.Date = task.Date;
                taskToAdd.Done = false;
                taskToAdd.Assingment = new Assignment
                {
                    AssignedTo = task.Assingment.AssignedTo,
                    CreatedBy = task.Assingment.CreatedBy
                };

                context.ToDoTasks.Add(taskToAdd);
                context.SaveChanges();   
            }

            return RedirectToAction("Index");
        }
    }
}

Day25_Backend/ToDoListApp - Day 2/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Day25_Backend/ToDoListApp - Day 2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ToDoListApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ToDoListApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ToDoListApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ToDoTask" asp-action="Index">ToDoTasks</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - ToDoListApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Day25_Backend/ToDoListApp - Day 2/Views/ToDoTask/Create.cshtml
@using ToDoTask = ToDoListApp.Entities.ToDoTask;
@model ToDoListApp.Entities.ToDoTask

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CreateNewTask">          
           
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" /> 
            </div>
            <div class="form-group">
                <label asp-for="Date" class="control-label"></label>
                <input asp-for="Date" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Assingment.CreatedBy" class="control-label"></label>
                <input asp-for="Assingment.CreatedBy" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Assingment.AssignedTo" class="control-label"></label>
                <input asp-for="Assingment.AssignedTo" class="form-control" />
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Day25_Backend/ToDoListApp - Day 2/Views/ToDoTask/Index.cshtml
@using ToDoTask = ToDoListApp.Entities.ToDoTask;
@model IEnumerable<ToDoTask>

@{
}

<h1>ToDoList</h1>

<p>
    @Html.ActionLink("Create a new task","Create")
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
           
            <th>
                @Html.DisplayNameFor(model => model.Date)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Assingment.CreatedBy)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Assingment .AssignedTo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Done)
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var task in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => task.Id)
                </td>
                <td>
                    @task.Name
                </td>
                
                <td>
                    @task.Date
                </td>
                 <td>
                    @task.Assingment.CreatedBy
                </td>
                <td>
                    @task.Assingment.AssignedTo
                </td>
                <td>
                    @task.Done
                </td>
            </tr>
        }
    </tbody>

</table>